### PR TITLE
switch to dune

### PR DESCRIPTION
**Pull request by redianthus**
Hi,

I switched the project to dune.

Cheers.

### CODE REVIEW

**Comment by jorisgio** [comment]
Thanks a lot. Any reason to remove opam file ?

**Comment by redianthus** [comment]
It's not removed but moved to `jemalloc_ctl.opam` because `dune` expects it to be named like this.

Also note that this changes the public name of the opam package (from `jemalloc` to `jemalloc_ctl`) as dune enforces the same name for the `opam` package and the library.

**Comment by jorisgio** [comment]
Right i just realized that. Thanks :ok:

**Comment by jorisgio** [comment]
I'm actually wondering if it is better to change "ocamlfind" package name instead, for opam repository. Will ask.

**Comment by redianthus** [comment]
As there seems to be no opam packages depending on this library it should be fine.

**Comment by jorisgio** [comment]
There is one (devkit). I actually think it is easier to change ocmalfind name and keep opam package and put version constraints.

**Comment by redianthus** [comment]
Ah, indeed, I missed it as it's optional.

**Pull request merged**
